### ISSUE TITLE
KeyDometStr<MyString, KeyDometSize::SIZE_64BIT> compatability

### ISSUE THREAD

**Issue by eliad93** [eliad93/keydomet_benchmark#1]
all benchmarks have a very similar call chain of functions, depending on the string type.
`KeyDometStr<MyString, KeyDometSize::SIZE_64BIT>` type doesn't have a suitable 
`makeFindKey(Container<KD, Args...>& s, const std::string& key)`
since Eran wrote the logic, it is best that he will give us a guide.

@okalinsk

**Comment by okalinsk** [comment]
@eliad93 
Eran suggested in his email to compare to std::string_view which is supported by Ketdomet.
We can discuss it further if u like.
