### ISSUE TITLE
Possible results explanation

### ISSUE THREAD

**Issue by eliad93** [eliad93/keydomet_benchmark#2]
I made some research to understand:
1 Why Eran's benchmarks run faster?
2. Why small benchmarks run slower?

My research suggests the following:
1. Eran's benchmarks uses a significantly improved keydomet code with many advanced micro optimizations like bitwise operators and metaprogramming. It also has another big advantage, and in what I think the most important one - it warms up the cache filling it with the relevant data.

2. One reason is as Eran suggested that it is too small to judge. It still bothered so I dag a little deeper, searching in google benchmark official forum and found this:
![image](https://user-images.githubusercontent.com/37880476/48915062-04e5d680-ee86-11e8-9ec8-b70d1934cb05.png)

I also saw that Eran is using the for(auto...) version while we are using the while(state.keeprunning) version. It is written that it can be an issue for small benchmarks. It also provides an explation to why I could'nt warm up the cache (tried in many ways) - it just pulls out state from memory in every iteration, twisting all the good cache work.
@okalinsk

**Comment by okalinsk** [comment]
Hi @eliad93 , Can you point to some specific examples for the first point?
Regarding the 2nd point, I guess it's easy to change and test?

**Comment by eliad93** [comment]
Hi Oren, thanks for the feedback.

1st point, I'll post an issue about one of these optimizations.

2nd point, I thought it would be easy and tried it the problem is that google benchmark evolves too and we are not syncronized with it (we used a kick off project wich uses google benchmark so its not trivial to sync it) so it fails to compile, with compilation errors: 'end' 'begin' not recognized for the range for loop.

**Comment by eliad93** [comment]
@erangi thanks for the comment!
I'm going to try running one of your benchmarks with keeprunning call, can you explain what did you do to get a container cached, I tried iterating over a container of keyDomet before the benchmark - didn't effect.
