### ISSUE TITLE
run generated strings lookup without benchmark for vtune

### ISSUE THREAD

**Issue by eliad93** [eliad93/keydomet_benchmark#24]

**Comment by eliad93** [comment]
here is a **24.2%** improvement in the absolute time it takes to make the comparisions.
it is clear that the results are not as good as we expect due to the creation of a keydometStr
from the std::string - if we count that too we get only **2%** improvement.

all this was done for **50k** lookups of strings with length **1024B**.

![image](https://user-images.githubusercontent.com/37880476/49403140-93930700-f754-11e8-88bb-cc9b3eeb2058.png)
![image](https://user-images.githubusercontent.com/37880476/49403162-a0175f80-f754-11e8-93eb-362ed7363acf.png)

@okalinsk

**Comment by eliad93** [comment]
**1M** lookups
the trend continues stronger with larger number of lookups
**29%** improvement for the lookup
only **5%** when taking keydometstr creation into account

![image](https://user-images.githubusercontent.com/37880476/49404021-ef5e8f80-f756-11e8-8ea7-d0c0143321ed.png)
![image](https://user-images.githubusercontent.com/37880476/49404427-1bc6db80-f758-11e8-9112-c174db5c6d15.png)

**Comment by eliad93** [comment]
**very important - no unnecessary memory allocations neither bugs found**

**Comment by eliad93** [comment]
@erangi thanks for the comment!
1. the size of the set was decided by @okalinsk in the benchmarks definition and is always the # of lookups.
2. Agreed - will perform additional benchmarks.
3. On the other hand - vtune measures the same way for both string and keydomet - thus it effects the same on both of them, why would coded counters have other results? - will try however.
4. used it, wanted to avoid function calls - will twist it to be inside the for loop.

**Comment by eliad93** [comment]
@erangi compilation error using makeFindKey in main finction: 
![image](https://user-images.githubusercontent.com/37880476/49498816-ecf25780-f874-11e8-9640-c6050dfa8e25.png)

**Comment by erangi** [comment]
Forgot to tell you - for makeFindKey to work, your container must use a _transparent comparator_... Namely, define the set as std::set<std::string, **std::less<>**>. You can also avoid makeFindKey and just use KeydometStr<string_view> on the lookups, since we know such a set can use it.
Regarding measuring timing yourself - my suggestion is to measure the whole loop from the outside, without counting anything inside it. It's true that VTune imposes the same overhead on all benchmarks, but think of it: if a string lookup takes 1 second, a keydomet lookup takes 0.5 second, and the vtune measurement takes another 100 seconds per lookup - what's the speedup you'll get?...

**Comment by eliad93** [comment]
I think we are getting too far from the target. original measurements were done using google benchmark, we got unexpected results - the speedup wasn't as good as the speedup in your generated @erangi benchmark - so we are now analyzing the results in order to explain them. my suggestion is to run the generated benchmark while creating all the keydomet str's before we measure instead of one by one. 
What is your opinion? @okalinsk

**Comment by okalinsk** [comment]
@erangi the improvements you get is for keyDomet that uses string_view or
string?
If the former, then it might explain the inconsistencies.

**Comment by erangi** [comment]
@okalinsk I evaluated a set<string> vs. set<kdmt<string>> and set<string_view> vs. set<kdmt<string_view>>. However, on the string variation, I avoid the extra allocation by comparing a kdmt<string_view> with the existing kdmt<string>s stored in the set. To avoid having the user think about it too much, I made makeFindKey part of the library.
@eliad93 Pre-generating the keydomet strings will indeed eliminate the need to using the string_views, but then you're not measuring the overhead of calculating the keydomet. This will make keydomet look better than it is. You can complete it with a separate measurement of the the keydomet creation if you want.
Anyway, I think you have all the pieces of the story now and a good understanding of what's going on. If you'd rather not use the string_view lookup, you can still explain the mediocre results with the allocation and demonstrate the good results you'd get if the allocation is avoided.

**Comment by eliad93** [comment]
vtune analysis proved right after string_view benchmark results
