### ISSUE TITLE
Results analysis

### ISSUE THREAD

**Issue by yanivbaldi** [eliad93/keydomet_benchmark#27]
Which results do we want to add to the existing document?
Eran noted that in some cases only tests with 1,000,000 searches are relevant, how to present the new results?

![image](https://user-images.githubusercontent.com/37808851/50736556-948ddd00-11c7-11e9-8c1e-278f095b6949.png)

**Comment by okalinsk** [comment]
The results that we discussed originally (including the smaller test sets)
