### ISSUE TITLE
run generated strings benchmark with 5M, 10M strings so vtune may help more than now

### ISSUE THREAD

**Issue by eliad93** [eliad93/keydomet_benchmark#4]

**Comment by okalinsk** [comment]
Try reducing the optimizations to -O2 or even -O0. It might be inlined by
the compiler.

**Comment by erangi** [comment]
I'm not even sure it's inlined - if the compiler knows lookup has no side effects, it can completely eliminate the call. In fact, if that's the case, it can also eliminate the complete for loop... try using lookup's value (say count the number of successful lookups) and print the result at the end, to force the compiler to make the calls. Google benchmark also has a function that does exactly that - [here](https://github.com/google/benchmark#preventing-optimisation).
Using lower optimization levels can provide a working baseline, but just to clarify what you probably know already - the profiling results of -O0 are meaningless. -O2 is reasonable, and if it provides useful information, you can also run the benchmarks (without profiling) on that compilation level.

**Comment by eliad93** [comment]
so let's clarify: 
the problem? can't dig deep enough in the code with vtune in the current state of things.
the solution? 
1. run my benchmark with vtune while forcing the for loop (I will use a counter and print the result) , if it works great, if not:
2. run with less optimization with vtune

anything missing or is'nt what you meant?

@erangi @okalinsk

**Comment by erangi** [comment]
What do you see on the assembly view? It's no fun trying to figure out what the code is doing, but you should at least get an idea if some functions are called during the lookup. Feel free to post a screenshot.
